apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web-app
  labels:
    app: nodejs-web-app
spec:
  selector:
    matchLabels:
      app: nodejs-web-app
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodejs-web-app
    spec:
      containers:
        - name: nodejs-web-app
          image: same7ammar/node-web-app-k8s
          ports:
            - containerPort: 3000
